---
- import_playbook: "./prerequisites.yml"
- hosts: localhost
  gather_facts: true
  tasks:
    - name: Customise Openshift Console
      include_role:
        name: customise-web-console
        tasks_from: install
    - name: Patch SSO URLs
      include_role:
        name: customise-web-console
        tasks_from: patch_sso

