---
- name: "get base sso url string to be updated"
  shell: "oc get route/sso -o jsonpath='{.spec.host}' -n {{ns_prefix | default('')}}sso"
  register: rhsso_route
  failed_when: rhsso_route.stderr != ""

- name: "set sso url as var"
  set_fact:
    rhsso_url: "https://{{ rhsso_route.stdout }}"

- debug: 
    msg: "{{rhsso_url}}"

- debug: 
    msg: "{{eval_sso_url_suffix}}"

- name: "save original web console config into variable and to backup file"
  shell: oc get cm web-console-config -n console-config -o yaml | tee /tmp/cm_web-console-config-map.yml
  register: web_console_output
  failed_when: web_console_output.stderr != ""
  when: eval_sso_url_suffix not in rhsso_url

- name: "append the sso suffix to sso url"
  when: eval_sso_url_suffix not in rhsso_url
  replace:
    path: /tmp/cm_web-console-config-map.yml
    regexp: "{{rhsso_url}}"
    replace: "{{rhsso_url}}{{eval_sso_url_suffix}}"

- name: "replace changed web console config map"
  shell: oc replace -f /tmp/cm_web-console-config-map.yml
  when: eval_sso_url_suffix not in rhsso_url
  register: output
  failed_when: output.rc != 0

